const { PrismaClient } = require('@prisma/client');
const db = new PrismaClient();

async function updateAndCleanRssSources() {
  console.log("=== Updating RSS Library & Cleaning Outdated Feeds ===");

  // 1. Find category and location IDs for smart mapping
  const categories = await db.category.findMany();
  const getCatId = (slug) => categories.find(c => c.slug === slug)?.id || null;

  const locations = await db.location.findMany();
  const getLocId = (slug) => locations.find(l => l.slug === slug)?.id || null;

  const jaunpurCatId = getCatId('jaunpur');
  const varanasiCatId = getCatId('varanasi');
  const upCatId = getCatId('uttar-pradesh');
  const deshCatId = getCatId('desh');
  const latestCatId = getCatId('latest');
  const manoranjanCatId = getCatId('manoranjan');
  const samajCatId = getCatId('samaj');

  const jaunpurLocId = getLocId('jaunpur');
  const varanasiLocId = getLocId('varanasi');
  const lucknowLocId = getLocId('lucknow');

  // 2. Remove unwanted foreign/dummy/duplicate sources
  const unwantedNames = [
    'Mashable Trending',
    'Reddit Videos',
    'Daily Mail Viral',
    'ESPN Sports',
    'Sportskeeda Cricket',
    'Cricket.com Feed',
    'Kitco Gold & Metals',
    'Investing.com Commodities',
    'BuzzFeed Viral',
    'Netflix Tudum',
    'TVLine Series',
    'Collider TV',
    'Variety Hollywood',
    'Deadline Hollywood',
    'Hollywood Reporter',
    'E Online',
    'TMZ Celebrity',
    'Screen Rant',
    'Variety Streaming',
    'Bollywood Hungama Box Office',
    'Koimoi Box Office',
    'Filmibeat Movies',
    'Cinema Express',
    // Duplicate old names
    'Live Hindustan UP',
    'Live Hindustan Varanasi',
    'Live Hindustan Jaunpur',
    'Amar Ujala UP',
    'Amar Ujala Varanasi',
    'Amar Ujala Jaunpur',
    'ABP UP',
    'Moneycontrol Gold & Finance'
  ];

  console.log(`Cleaning up ${unwantedNames.length} outdated/dummy/duplicate sources...`);
  const deleteResult = await db.newsSource.deleteMany({
    where: {
      name: { in: unwantedNames }
    }
  });
  console.log(`Deleted ${deleteResult.count} unwanted sources.`);

  // 3. Define the production verified, unverified, and failed sources
  const feedLibrary = [
    // --- LIVE HINDUSTAN ---
    {
      name: 'Live Hindustan | Jaunpur',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Jaunpur',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Jaunpur',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/jaunpur/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh/jaunpur',
      defaultCategoryId: jaunpurCatId,
      defaultLocationId: jaunpurLocId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Live Hindustan | Varanasi',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Varanasi',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Varanasi',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/varanasi/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh/varanasi',
      defaultCategoryId: varanasiCatId,
      defaultLocationId: varanasiLocId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Live Hindustan | Lucknow',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Lucknow',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Lucknow',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/lucknow/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh/lucknow',
      defaultCategoryId: upCatId,
      defaultLocationId: lucknowLocId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Live Hindustan | Uttar Pradesh',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Uttar Pradesh',
      country: 'India',
      state: 'Uttar Pradesh',
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh',
      defaultCategoryId: upCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Live Hindustan | Desh (National)',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'National',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/national/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/national',
      defaultCategoryId: deshCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Live Hindustan | Breaking News',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Breaking News',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/breaking-news/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/breaking-news',
      defaultCategoryId: latestCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Live Hindustan | Film Reviews',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Entertainment',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/entertainment/reviews/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/entertainment',
      defaultCategoryId: manoranjanCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 30,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Live Hindustan | Vichar (Editorial)',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Editorial',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/opinion/vichar/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/opinion',
      defaultCategoryId: samajCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 30,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },

    // --- AMAR UJALA ---
    {
      name: 'Amar Ujala | Varanasi',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Regional News',
      region: 'Varanasi',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Varanasi',
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/varanasi.xml',
      websiteUrl: 'https://www.amarujala.com/uttar-pradesh/varanasi',
      defaultCategoryId: varanasiCatId,
      defaultLocationId: varanasiLocId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Amar Ujala | Jaunpur',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Regional News',
      region: 'Jaunpur',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Jaunpur',
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/jaunpur.xml',
      websiteUrl: 'https://www.amarujala.com/uttar-pradesh/jaunpur',
      defaultCategoryId: jaunpurCatId,
      defaultLocationId: jaunpurLocId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Amar Ujala | Uttar Pradesh',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Regional News',
      region: 'Uttar Pradesh',
      country: 'India',
      state: 'Uttar Pradesh',
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/uttar-pradesh.xml',
      websiteUrl: 'https://www.amarujala.com/uttar-pradesh',
      defaultCategoryId: upCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Amar Ujala | Breaking News',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Breaking News',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/breaking-news.xml',
      websiteUrl: 'https://www.amarujala.com/breaking-news',
      defaultCategoryId: latestCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },

    // --- DAINIK BHASKAR ---
    {
      name: 'Dainik Bhaskar | National',
      publisherName: 'Dainik Bhaskar',
      logoUrl: 'https://www.bhaskar.com/favicon.ico',
      category: 'National',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://www.bhaskar.com/rss-feed/1061/',
      websiteUrl: 'https://www.bhaskar.com/national/',
      defaultCategoryId: deshCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },

    // --- DAINIK JAGRAN ---
    {
      name: 'Dainik Jagran | National',
      publisherName: 'Dainik Jagran',
      logoUrl: 'https://www.jagran.com/favicon.ico',
      category: 'National',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://rss.jagran.com/rss/news/national.xml',
      websiteUrl: 'https://www.jagran.com/news/national-news-hindi.html',
      defaultCategoryId: deshCatId,
      defaultLocationId: null,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
      verificationStatus: 'VERIFIED',
      healthStatus: 'Healthy',
      lastError: null,
    },
    {
      name: 'Dainik Jagran | Uttar Pradesh',
      publisherName: 'Dainik Jagran',
      logoUrl: 'https://www.jagran.com/favicon.ico',
      category: 'Regional News',
      region: 'Uttar Pradesh',
      country: 'India',
      state: 'Uttar Pradesh',
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://rss.jagran.com/rss/news/uttar-pradesh.xml',
      websiteUrl: 'https://www.jagran.com/uttar-pradesh',
      defaultCategoryId: upCatId,
      defaultLocationId: null,
      isActive: false,
      autoSync: false,
      syncInterval: 15,
      verificationStatus: 'UNVERIFIED',
      healthStatus: 'Warning',
      lastError: 'Dainik Jagran feed requires verification/configuration.',
    },
    {
      name: 'Dainik Jagran | Lucknow',
      publisherName: 'Dainik Jagran',
      logoUrl: 'https://www.jagran.com/favicon.ico',
      category: 'Regional News',
      region: 'Lucknow',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Lucknow',
      sourceType: 'RSS',
      feedUrl: 'https://rss.jagran.com/rss/news/lucknow.xml',
      websiteUrl: 'https://www.jagran.com/uttar-pradesh/lucknow-city.html',
      defaultCategoryId: upCatId,
      defaultLocationId: lucknowLocId,
      isActive: false,
      autoSync: false,
      syncInterval: 15,
      verificationStatus: 'UNVERIFIED',
      healthStatus: 'Warning',
      lastError: 'Dainik Jagran feed requires verification/configuration.',
    },
    {
      name: 'Dainik Jagran | Varanasi',
      publisherName: 'Dainik Jagran',
      logoUrl: 'https://www.jagran.com/favicon.ico',
      category: 'Regional News',
      region: 'Varanasi',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Varanasi',
      sourceType: 'RSS',
      feedUrl: 'https://rss.jagran.com/rss/news/varanasi.xml',
      websiteUrl: 'https://www.jagran.com/uttar-pradesh/varanasi-city.html',
      defaultCategoryId: varanasiCatId,
      defaultLocationId: varanasiLocId,
      isActive: false,
      autoSync: false,
      syncInterval: 15,
      verificationStatus: 'UNVERIFIED',
      healthStatus: 'Warning',
      lastError: 'Dainik Jagran feed requires verification/configuration.',
    },
    {
      name: 'Dainik Jagran | Jaunpur',
      publisherName: 'Dainik Jagran',
      logoUrl: 'https://www.jagran.com/favicon.ico',
      category: 'Regional News',
      region: 'Jaunpur',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Jaunpur',
      sourceType: 'RSS',
      feedUrl: 'https://rss.jagran.com/rss/news/jaunpur.xml',
      websiteUrl: 'https://www.jagran.com/uttar-pradesh/jaunpur.html',
      defaultCategoryId: jaunpurCatId,
      defaultLocationId: jaunpurLocId,
      isActive: false,
      autoSync: false,
      syncInterval: 15,
      verificationStatus: 'UNVERIFIED',
      healthStatus: 'Warning',
      lastError: 'Dainik Jagran feed requires verification/configuration.',
    },

    // --- NAVBHARAT TIMES (Main - Endpoint Deprecated 404) ---
    {
      name: 'Navbharat Times | Main',
      publisherName: 'Navbharat Times',
      logoUrl: 'https://navbharattimes.indiatimes.com/favicon.ico',
      category: 'National',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://navbharattimes.indiatimes.com/rssfeedsdefault.cms',
      websiteUrl: 'https://navbharattimes.indiatimes.com',
      defaultCategoryId: deshCatId,
      defaultLocationId: null,
      isActive: false,
      autoSync: false,
      syncInterval: 30,
      verificationStatus: 'FAILED',
      healthStatus: 'Failed',
      lastError: 'HTTP 404 (Feed endpoint deprecated by publisher)',
    },

    // --- JANSATTA (Main - Endpoint Retired 410) ---
    {
      name: 'Jansatta | Main',
      publisherName: 'Jansatta',
      logoUrl: 'https://www.jansatta.com/favicon.ico',
      category: 'National',
      region: 'National',
      country: 'India',
      state: null,
      city: null,
      sourceType: 'RSS',
      feedUrl: 'https://www.jansatta.com/feed/',
      websiteUrl: 'https://www.jansatta.com',
      defaultCategoryId: deshCatId,
      defaultLocationId: null,
      isActive: false,
      autoSync: false,
      syncInterval: 30,
      verificationStatus: 'FAILED',
      healthStatus: 'Failed',
      lastError: 'HTTP 410 (Feed retired/gone by Indian Express Group)',
    },
  ];

  console.log(`Upserting ${feedLibrary.length} production feeds...`);
  for (const s of feedLibrary) {
    const existing = await db.newsSource.findFirst({
      where: {
        OR: [
          { name: s.name },
          { feedUrl: s.feedUrl }
        ]
      }
    });

    if (!existing) {
      await db.newsSource.create({ data: s });
      console.log(`[Created] ${s.name} (${s.verificationStatus})`);
    } else {
      await db.newsSource.update({
        where: { id: existing.id },
        data: s,
      });
      console.log(`[Updated] ${s.name} (${s.verificationStatus})`);
    }
  }

  console.log("=== RSS Library Update & Cleanup Completed Successfully! ===");
}

updateAndCleanRssSources()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Error updating RSS library:", err);
    process.exit(1);
  });
