const { PrismaClient } = require('@prisma/client');
const db = new PrismaClient();

async function seedPredefinedRssLibrary() {
  console.log("Seeding Regional News and Entertainment/Special Content RSS Sources into Dainik Manyavar CMS...");

  const manoranjanCat = await db.category.findUnique({ where: { slug: 'manoranjan' } });
  const cricketCat = await db.category.findUnique({ where: { slug: 'cricket' } });
  const goldSilverCat = await db.category.findUnique({ where: { slug: 'gold-silver' } });

  const manoranjanCatId = manoranjanCat ? manoranjanCat.id : null;
  const cricketCatId = cricketCat ? cricketCat.id : manoranjanCatId;
  const goldSilverCatId = goldSilverCat ? goldSilverCat.id : null;

  const sources = [
    // 15 REGIONAL NEWS RSS SOURCES (LIVE HINDUSTAN, AMAR UJALA, ABP LIVE)
    {
      name: 'Live Hindustan | Uttar Pradesh',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Uttar Pradesh',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Live Hindustan | Varanasi',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Varanasi',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/varanasi/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh/varanasi',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Live Hindustan | Jaunpur',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Jaunpur',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/jaunpur/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh/jaunpur',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Live Hindustan | Ghazipur',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Ghazipur',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/ghazipur/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh/ghazipur',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Live Hindustan | Chandauli',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Chandauli',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/uttar-pradesh/chandauli/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/uttar-pradesh/chandauli',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Live Hindustan | New Delhi',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'New Delhi',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/ncr/new-delhi/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/ncr/new-delhi',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Live Hindustan | Bihar',
      publisherName: 'Live Hindustan',
      logoUrl: 'https://www.livehindustan.com/favicon.ico',
      category: 'Regional News',
      region: 'Bihar',
      sourceType: 'RSS',
      feedUrl: 'https://api.livehindustan.com/feeds/rss/bihar/rssfeed.xml',
      websiteUrl: 'https://www.livehindustan.com/bihar',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Amar Ujala | Uttar Pradesh',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Regional News',
      region: 'Uttar Pradesh',
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/uttar-pradesh.xml',
      websiteUrl: 'https://www.amarujala.com/uttar-pradesh',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Amar Ujala | Varanasi',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Regional News',
      region: 'Varanasi',
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/varanasi.xml',
      websiteUrl: 'https://www.amarujala.com/uttar-pradesh/varanasi',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Amar Ujala | Jaunpur',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Regional News',
      region: 'Jaunpur',
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/jaunpur.xml',
      websiteUrl: 'https://www.amarujala.com/uttar-pradesh/jaunpur',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Amar Ujala | Delhi NCR',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Regional News',
      region: 'Delhi NCR',
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/delhi-ncr.xml',
      websiteUrl: 'https://www.amarujala.com/delhi-ncr',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Amar Ujala | Bihar',
      publisherName: 'Amar Ujala',
      logoUrl: 'https://www.amarujala.com/favicon.ico',
      category: 'Regional News',
      region: 'Bihar',
      sourceType: 'RSS',
      feedUrl: 'https://www.amarujala.com/rss/bihar.xml',
      websiteUrl: 'https://www.amarujala.com/bihar',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'ABP Live Hindi | Uttar Pradesh / Uttarakhand',
      publisherName: 'ABP Live',
      logoUrl: 'https://www.abplive.com/favicon.ico',
      category: 'Regional News',
      region: 'Uttar Pradesh',
      sourceType: 'RSS',
      feedUrl: 'https://www.abplive.com/news/states/up-uk/feed',
      websiteUrl: 'https://www.abplive.com/news/states/up-uk',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'ABP Live Hindi | Delhi NCR',
      publisherName: 'ABP Live',
      logoUrl: 'https://www.abplive.com/favicon.ico',
      category: 'Regional News',
      region: 'Delhi NCR',
      sourceType: 'RSS',
      feedUrl: 'https://www.abplive.com/news/states/delhi-ncr/feed',
      websiteUrl: 'https://www.abplive.com/news/states/delhi-ncr',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'ABP Live Hindi | Bihar',
      publisherName: 'ABP Live',
      logoUrl: 'https://www.abplive.com/favicon.ico',
      category: 'Regional News',
      region: 'Bihar',
      sourceType: 'RSS',
      feedUrl: 'https://www.abplive.com/news/states/bihar/feed',
      websiteUrl: 'https://www.abplive.com/news/states/bihar',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },

    // ENTERTAINMENT / BOLLYWOOD / MOVIES
    {
      name: 'Bollywood Hungama',
      publisherName: 'Bollywood Hungama',
      logoUrl: 'https://www.bollywoodhungama.com/favicon.ico',
      category: 'Entertainment',
      region: 'Bollywood',
      sourceType: 'RSS',
      feedUrl: 'https://www.bollywoodhungama.com/feed/',
      websiteUrl: 'https://www.bollywoodhungama.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Bollywood Life',
      publisherName: 'Bollywood Life',
      logoUrl: 'https://www.bollywoodlife.com/favicon.ico',
      category: 'Entertainment',
      region: 'Bollywood',
      sourceType: 'RSS',
      feedUrl: 'https://www.bollywoodlife.com/feed/',
      websiteUrl: 'https://www.bollywoodlife.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Pinkvilla Entertainment',
      publisherName: 'Pinkvilla',
      logoUrl: 'https://www.pinkvilla.com/favicon.ico',
      category: 'Entertainment',
      region: 'Bollywood',
      sourceType: 'RSS',
      feedUrl: 'https://www.pinkvilla.com/rss/',
      websiteUrl: 'https://www.pinkvilla.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Koimoi',
      publisherName: 'Koimoi',
      logoUrl: 'https://www.koimoi.com/favicon.ico',
      category: 'Entertainment',
      region: 'Bollywood',
      sourceType: 'RSS',
      feedUrl: 'https://www.koimoi.com/feed/',
      websiteUrl: 'https://www.koimoi.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Filmfare',
      publisherName: 'Filmfare',
      logoUrl: 'https://www.filmfare.com/favicon.ico',
      category: 'Entertainment',
      region: 'Bollywood',
      sourceType: 'RSS',
      feedUrl: 'https://www.filmfare.com/rss/',
      websiteUrl: 'https://www.filmfare.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Indian Express Entertainment',
      publisherName: 'Indian Express',
      logoUrl: 'https://indianexpress.com/favicon.ico',
      category: 'Entertainment',
      region: 'Bollywood',
      sourceType: 'RSS',
      feedUrl: 'https://indianexpress.com/section/entertainment/feed/',
      websiteUrl: 'https://indianexpress.com/section/entertainment',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Times of India Entertainment',
      publisherName: 'Times of India',
      logoUrl: 'https://timesofindia.indiatimes.com/favicon.ico',
      category: 'Entertainment',
      region: 'Bollywood',
      sourceType: 'RSS',
      feedUrl: 'https://timesofindia.indiatimes.com/rssfeeds/1081479906.cms',
      websiteUrl: 'https://timesofindia.indiatimes.com/entertainment',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },

    // HOLLYWOOD / INTERNATIONAL ENTERTAINMENT
    {
      name: 'Variety Hollywood',
      publisherName: 'Variety',
      logoUrl: 'https://variety.com/favicon.ico',
      category: 'Entertainment',
      region: 'Hollywood',
      sourceType: 'RSS',
      feedUrl: 'https://variety.com/feed/',
      websiteUrl: 'https://variety.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Deadline Hollywood',
      publisherName: 'Deadline',
      logoUrl: 'https://deadline.com/favicon.ico',
      category: 'Entertainment',
      region: 'Hollywood',
      sourceType: 'RSS',
      feedUrl: 'https://deadline.com/feed/',
      websiteUrl: 'https://deadline.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Hollywood Reporter',
      publisherName: 'The Hollywood Reporter',
      logoUrl: 'https://www.hollywoodreporter.com/favicon.ico',
      category: 'Entertainment',
      region: 'Hollywood',
      sourceType: 'RSS',
      feedUrl: 'https://www.hollywoodreporter.com/feed/',
      websiteUrl: 'https://www.hollywoodreporter.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'E Online',
      publisherName: 'E! Online',
      logoUrl: 'https://eonline.com/favicon.ico',
      category: 'Entertainment',
      region: 'Hollywood',
      sourceType: 'RSS',
      feedUrl: 'https://eonline.com/syndication/feeds/rssfeeds/topstories.xml',
      websiteUrl: 'https://eonline.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'TMZ Celebrity',
      publisherName: 'TMZ',
      logoUrl: 'https://www.tmz.com/favicon.ico',
      category: 'Entertainment',
      region: 'Hollywood',
      sourceType: 'RSS',
      feedUrl: 'https://www.tmz.com/rss.xml',
      websiteUrl: 'https://www.tmz.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Screen Rant',
      publisherName: 'Screen Rant',
      logoUrl: 'https://screenrant.com/favicon.ico',
      category: 'Entertainment',
      region: 'Hollywood',
      sourceType: 'RSS',
      feedUrl: 'https://screenrant.com/feed/',
      websiteUrl: 'https://screenrant.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },

    // BOX OFFICE / MOVIE COLLECTION
    {
      name: 'Bollywood Hungama Box Office',
      publisherName: 'Bollywood Hungama',
      logoUrl: 'https://www.bollywoodhungama.com/favicon.ico',
      category: 'Entertainment',
      region: 'Box Office',
      sourceType: 'RSS',
      feedUrl: 'https://www.bollywoodhungama.com/feed/',
      websiteUrl: 'https://www.bollywoodhungama.com/box-office-collections/',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Koimoi Box Office',
      publisherName: 'Koimoi',
      logoUrl: 'https://www.koimoi.com/favicon.ico',
      category: 'Entertainment',
      region: 'Box Office',
      sourceType: 'RSS',
      feedUrl: 'https://www.koimoi.com/feed/',
      websiteUrl: 'https://www.koimoi.com/box-office/',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Filmibeat Movies',
      publisherName: 'Filmibeat',
      logoUrl: 'https://www.filmibeat.com/favicon.ico',
      category: 'Entertainment',
      region: 'Box Office',
      sourceType: 'RSS',
      feedUrl: 'https://www.filmibeat.com/rss/',
      websiteUrl: 'https://www.filmibeat.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Cinema Express',
      publisherName: 'Cinema Express',
      logoUrl: 'https://www.cinemaexpress.com/favicon.ico',
      category: 'Entertainment',
      region: 'Box Office',
      sourceType: 'RSS',
      feedUrl: 'https://www.cinemaexpress.com/rss',
      websiteUrl: 'https://www.cinemaexpress.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },

    // OTT / WEB SERIES
    {
      name: 'Netflix Tudum',
      publisherName: 'Netflix',
      logoUrl: 'https://assets.nflxext.com/ffe/siteui/common/icons/nficon2016.ico',
      category: 'Entertainment',
      region: 'OTT',
      sourceType: 'RSS',
      feedUrl: 'https://www.netflix.com/tudum/rss',
      websiteUrl: 'https://www.netflix.com/tudum',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Variety Streaming',
      publisherName: 'Variety',
      logoUrl: 'https://variety.com/favicon.ico',
      category: 'Entertainment',
      region: 'OTT',
      sourceType: 'RSS',
      feedUrl: 'https://variety.com/v/streaming/feed/',
      websiteUrl: 'https://variety.com/v/streaming/',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'TVLine Series',
      publisherName: 'TVLine',
      logoUrl: 'https://tvline.com/favicon.ico',
      category: 'Entertainment',
      region: 'OTT',
      sourceType: 'RSS',
      feedUrl: 'https://tvline.com/feed/',
      websiteUrl: 'https://tvline.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Collider TV',
      publisherName: 'Collider',
      logoUrl: 'https://collider.com/favicon.ico',
      category: 'Entertainment',
      region: 'OTT',
      sourceType: 'RSS',
      feedUrl: 'https://collider.com/tv/feed/',
      websiteUrl: 'https://collider.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },

    // VIRAL VIDEOS / TRENDING
    {
      name: 'BuzzFeed Viral',
      publisherName: 'BuzzFeed',
      logoUrl: 'https://www.buzzfeed.com/favicon.ico',
      category: 'Entertainment',
      region: 'Viral',
      sourceType: 'RSS',
      feedUrl: 'https://www.buzzfeed.com/feeds.xml',
      websiteUrl: 'https://www.buzzfeed.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Mashable Trending',
      publisherName: 'Mashable',
      logoUrl: 'https://mashable.com/favicon.ico',
      category: 'Entertainment',
      region: 'Viral',
      sourceType: 'RSS',
      feedUrl: 'https://mashable.com/feeds/rss',
      websiteUrl: 'https://mashable.com',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Reddit Videos',
      publisherName: 'Reddit',
      logoUrl: 'https://www.reddit.com/favicon.ico',
      category: 'Entertainment',
      region: 'Viral',
      sourceType: 'RSS',
      feedUrl: 'https://www.reddit.com/r/videos/.rss',
      websiteUrl: 'https://www.reddit.com/r/videos',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Daily Mail Viral',
      publisherName: 'Daily Mail',
      logoUrl: 'https://www.dailymail.co.uk/favicon.ico',
      category: 'Entertainment',
      region: 'Viral',
      sourceType: 'RSS',
      feedUrl: 'https://www.dailymail.co.uk/articles.rss',
      websiteUrl: 'https://www.dailymail.co.uk',
      defaultCategoryId: manoranjanCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },

    // CRICKET RSS SOURCES
    {
      name: 'ESPN Cricinfo',
      publisherName: 'ESPN Cricinfo',
      category: 'Cricket',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml',
      defaultCategoryId: cricketCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'ESPN Sports',
      publisherName: 'ESPN',
      category: 'Cricket',
      region: 'Global',
      sourceType: 'RSS',
      feedUrl: 'https://www.espn.com/espn/rss/news',
      websiteUrl: 'https://www.espn.com',
      defaultCategoryId: cricketCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Sportskeeda Cricket',
      publisherName: 'Sportskeeda',
      category: 'Cricket',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://www.sportskeeda.com/feed',
      websiteUrl: 'https://www.sportskeeda.com/cricket',
      defaultCategoryId: cricketCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Cricket.com Feed',
      publisherName: 'Cricket.com',
      category: 'Cricket',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://www.cricket.com/rss',
      websiteUrl: 'https://www.cricket.com',
      defaultCategoryId: cricketCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Google News Cricket Hindi',
      publisherName: 'Google News',
      category: 'Cricket',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://news.google.com/rss/search?q=क्रिकेट+भारत&hl=hi&gl=IN&ceid=IN:hi',
      defaultCategoryId: cricketCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },

    // RASHIFAL SOURCES
    {
      name: 'Google News Daily Rashifal',
      publisherName: 'Google News',
      category: 'Rashifal',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://news.google.com/rss/search?q=आज+का+राशिफल+हिंदी&hl=hi&gl=IN&ceid=IN:hi',
      isActive: true,
      autoSync: true,
      syncInterval: 60,
    },

    // STOCK MARKET SOURCES
    {
      name: 'Moneycontrol Market',
      publisherName: 'Moneycontrol',
      category: 'Stock Market',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://www.moneycontrol.com/rss/MCtopnews.xml',
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },

    // GOLD SILVER / MARKET SOURCES
    {
      name: 'Economic Times Markets',
      publisherName: 'Economic Times',
      category: 'Gold Silver',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms',
      websiteUrl: 'https://economictimes.indiatimes.com/markets',
      defaultCategoryId: goldSilverCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Moneycontrol Gold & Finance',
      publisherName: 'Moneycontrol',
      category: 'Gold Silver',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://www.moneycontrol.com/rss/',
      websiteUrl: 'https://www.moneycontrol.com',
      defaultCategoryId: goldSilverCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Kitco Gold & Metals',
      publisherName: 'Kitco',
      category: 'Gold Silver',
      region: 'Global',
      sourceType: 'RSS',
      feedUrl: 'https://www.kitco.com/rss/',
      websiteUrl: 'https://www.kitco.com',
      defaultCategoryId: goldSilverCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Investing.com Commodities',
      publisherName: 'Investing.com',
      category: 'Gold Silver',
      region: 'Global',
      sourceType: 'RSS',
      feedUrl: 'https://www.investing.com/rss/',
      websiteUrl: 'https://www.investing.com',
      defaultCategoryId: goldSilverCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 15,
    },
    {
      name: 'Google Gold Silver Hindi',
      publisherName: 'Google News',
      category: 'Gold Silver',
      region: 'India',
      sourceType: 'RSS',
      feedUrl: 'https://news.google.com/rss/search?q=सोना+चांदी+भाव+हिंदी&hl=hi&gl=IN&ceid=IN:hi',
      defaultCategoryId: goldSilverCatId,
      isActive: true,
      autoSync: true,
      syncInterval: 60,
    },
  ];

  for (const s of sources) {
    const existing = await db.newsSource.findFirst({
      where: { name: s.name },
    });

    if (!existing) {
      await db.newsSource.create({ data: s });
    } else {
      await db.newsSource.update({
        where: { id: existing.id },
        data: s,
      });
    }
  }

  console.log(`[+] Predefined RSS Library seeded with ${sources.length} regional and special news sources!`);
}

seedPredefinedRssLibrary()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
